django 실습/my_practice_0924/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('update/', views.update, name='update'),
]

django 실습/my_practice_0924/articles/views.py
from django.shortcuts import render, redirect
# 모델 클래스 가져오기
from .models import Article

# Create your views here.
def index(request):
    # 게시글 전체 조회 요청 to DB
    articles = Article.objects.all()
    # 게시글은 보통 역순으로 보이므로 재정렬
    articles = sorted(list(articles), key=lambda x: x.pk, reverse=True)
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)

def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article': article,
    }
    return render(request, 'articles/detail.html', context)

def new(request):
    return render(request, 'articles/new.html')

def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')
    article = Article(title = title, content = content)
    article.save()
    return redirect('articles:detail', article.pk)

def delete(request):
    pk = request.POST.get('pk')
    article = Article.objects.get(pk=pk)
    article.delete()
    return redirect('articles:index')

def edit(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article': article,
    }
    return render(request, 'articles/edit.html', context)

def update(request):
    pk = request.POST.get('pk')
    title = request.POST.get('title')
    content = request.POST.get('content')
    article = Article.objects.get(pk=pk)
    article.title = title
    article.content = content
    article.save()
    return redirect('articles:detail', pk)

django 실습/my_practice_0924/articles/templates/articles/create.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>게시글이 작성 되었습니다.</h1>
  <a href="{% url "articles:index" %}">HOME</a>
</body>
</html>

django 실습/my_practice_0924/articles/templates/articles/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h2>DETAIL</h2>
  <h3>{{ article.pk }}번째 글</h3>
  <hr>
  <p>제목: {{ article.title }}</p>
  <p>내용: {{ article.content }}</p>
  <p>작성일: {{ article.created_at }}</p>
  <p>수정일: {{ article.updated_at }}</p>
  <hr>
  <a href="{% url "articles:edit" article.pk %}">edit</a>
  <form action="{% url "articles:delete" %}" method="POST">
    {% csrf_token %}
    <input type="hidden" name="pk" value="{{article.pk}}">
    <input type="submit" value="DELETE">
  </form>
  <a href="{% url "articles:index" %}">[BACK]</a>
</body>
</html>

django 실습/my_practice_0924/articles/templates/articles/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>EDIT</h1>
  <form action="{% url "articles:update" %}" method="POST">
    {% csrf_token %}
    <input type="hidden" name="pk" value="{{ article.pk }}">
    <div>
      <label for="title">Title : </label>
      <input type="text" name="title" id="title" value="{{ article.title }}">
    </div>
    <div>
      <label for="content">Content : </label>
      <textarea name="content" id="content">{{ article.content }}</textarea>
    </div>
    <input type="submit" value="UPDATE">
  </form>
  <hr>
  <a href="{% url "articles:detail" article.pk %}">[BACK]</a>
</body>
</html>

django 실습/my_practice_0924/articles/templates/articles/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Articles</h1>
  <a href="{% url "articles:new" %}">NEW</a>
  <hr>
  {% for article in articles %}
    <p>글 번호: {{ article.pk }}</p>
    <a href="{% url "articles:detail" article.pk %}">
      <p>글 제목: {{ article.title }}</p>
    </a>
    <p>글 내용: {{ article.content }}</p>
    <hr>
  {% endfor %}

</body>
</html>

django 실습/my_practice_0924/articles/templates/articles/new.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>NEW</h1>
  <form action="{% url "articles:create" %}" method="POST">
    {% csrf_token %}
    <div>
      <label for="title">Title: </label>
      <input type="text" name="title" id="title">
    </div>
    <div>
      <label for="content">Content: </label>
      <Textarea name="content" id="content"></Textarea>
    </div>
    <input type="submit" value="제출">
  </form>
  <hr>
  <a href="{% url "articles:index" %}">[BACK]</a>
</body>
</html>