django 실습/my_practice_0919/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"
urlpatterns = [
    path('index/', views.index, name='index'),
    path('dinner/', views.dinner, name='dinner'),
    path('login/', views.login, name='login'),
]

django 실습/my_practice_0919/firstpjt/urls.py
from django.contrib import admin
from django.urls import path, include
from articles import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("articles/", include("articles.urls")),
]

django 실습/my_practice_0919/articles/views.py
# import random
from django.shortcuts import render
import random


# Create your views here.
def index(request):
    if request.GET:
        user_id = request.GET.get('user-id')
        context = {
            'name' : user_id,
        }
        return render(request, 'articles/index.html', context)
    context = {
        'name' : '사용자',
    }
    return render(request, 'articles/index.html', context)


def dinner(request):
    foods = ['국밥', '국수', '카레', '탕수육',]
    picked = random.choice(foods)
    context = {
        'foods' : foods,
        'picked' : picked,
    }
    return render(request, 'articles/dinner.html', context)


def login(request):
    return render(request, 'articles/login.html')

django 실습/my_practice_0919/articles/templates/articles/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <style>
  nav>a {
      text-decoration : none;
      color : skyblue;
    }
  </style>
</head>
<body>
  <nav>
    <a href={% url "articles:index" %}>홈</a>
    <a href={% url "articles:dinner" %}>저녁메뉴</a>
    <a href={% url "articles:login" %}>로그인</a>
  </nav>
  {% block content%}
  {% endblock content%}
</body>
</html>

django 실습/my_practice_0919/articles/templates/articles/dinner.html
<!-- articles.dinner.html -->

{% extends "articles/base.html" %}

{% block content %}
  <p>{{ picked }} 메뉴는 {{ picked|length }}글자 입니다.</p>
  <h2>메뉴판</h2>
  <ul>
    {% for food in foods %}
      <li>{{ food }}</li>
    {% endfor %}
  </ul>
  {% if foods|length == 0 %}
    <p>메뉴가 소진 되었습니다.</p>
  {% else %}
    <p>아직 메뉴가 남았습니다.</p>
  {% endif %}
{% endblock content %}

django 실습/my_practice_0919/articles/templates/articles/index.html
<!-- articles.index.html -->

{% extends "articles/base.html" %}
{% block content %}
  <h1>안녕하세요! {{name}}님!</h1>
{% endblock content %}

django 실습/my_practice_0919/articles/templates/articles/login.html
<!-- articles.login.html -->
{% extends "articles/base.html" %}
{% block content %}
  <form action="http://localhost:8000/index" method="get">
    <label for="user-id">USER_ID : </label>
    <input type="text" name="user-id" id="user-id"><br>
    <label for="user-pw">PASSWORD : </label>
    <input type="password" name="user-pw" id="user-pw"><br>
    <input type="submit" value="로그인">
  </form>
{% endblock content %}